# Generated by Django 5.0.4 on 2024-04-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_gu_name', models.CharField(max_length=100)),
                ('m_type_code', models.CharField(max_length=10)),
                ('a_name', models.CharField(max_length=100)),
                ('a_price', models.IntegerField()),
                ('p_seq', models.IntegerField()),
                ('m_type_name', models.CharField(max_length=100)),
                ('a_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('m_gu_code', models.CharField(max_length=10)),
                ('add_col', models.CharField(blank=True, max_length=100, null=True)),
                ('m_name', models.CharField(max_length=100)),
                ('p_date', models.DateField()),
                ('p_year_month', models.CharField(max_length=10)),
                ('a_seq', models.IntegerField()),
                ('m_seq', models.IntegerField()),
            ],
        ),
    ]
