# Generated by Django 5.0.4 on 2024-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_seq', models.IntegerField(unique=True)),
                ('n_title', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField()),
                ('n_view_count', models.IntegerField()),
                ('file_path', models.URLField(blank=True, null=True)),
                ('n_contents', models.TextField()),
            ],
        ),
    ]
